import {StateGapMapGeometry} from './types';

export const STATE_GAP_MAP_GEOMETRIES: StateGapMapGeometry[] = [
  {code: 'AL', displayRegion: 'contiguous'},
  {code: 'AK', displayRegion: 'alaskaInset'},
  {code: 'AZ', displayRegion: 'contiguous'},
  {code: 'AR', displayRegion: 'contiguous'},
  {code: 'CA', displayRegion: 'contiguous'},
  {code: 'CO', displayRegion: 'contiguous'},
  {code: 'CT', displayRegion: 'contiguous'},
  {code: 'DE', displayRegion: 'contiguous'},
  {code: 'FL', displayRegion: 'contiguous'},
  {code: 'GA', displayRegion: 'contiguous'},
  {code: 'HI', displayRegion: 'hawaiiInset'},
  {code: 'ID', displayRegion: 'contiguous'},
  {code: 'IL', displayRegion: 'contiguous'},
  {code: 'IN', displayRegion: 'contiguous'},
  {code: 'IA', displayRegion: 'contiguous'},
  {code: 'KS', displayRegion: 'contiguous'},
  {code: 'KY', displayRegion: 'contiguous'},
  {code: 'LA', displayRegion: 'contiguous'},
  {code: 'ME', displayRegion: 'contiguous'},
  {code: 'MD', displayRegion: 'contiguous'},
  {code: 'MA', displayRegion: 'contiguous'},
  {code: 'MI', displayRegion: 'contiguous'},
  {code: 'MN', displayRegion: 'contiguous'},
  {code: 'MS', displayRegion: 'contiguous'},
  {code: 'MO', displayRegion: 'contiguous'},
  {code: 'MT', displayRegion: 'contiguous'},
  {code: 'NE', displayRegion: 'contiguous'},
  {code: 'NV', displayRegion: 'contiguous'},
  {code: 'NH', displayRegion: 'contiguous'},
  {code: 'NJ', displayRegion: 'contiguous'},
  {code: 'NM', displayRegion: 'contiguous'},
  {code: 'NY', displayRegion: 'contiguous'},
  {code: 'NC', displayRegion: 'contiguous'},
  {code: 'ND', displayRegion: 'contiguous'},
  {code: 'OH', displayRegion: 'contiguous'},
  {code: 'OK', displayRegion: 'contiguous'},
  {code: 'OR', displayRegion: 'contiguous'},
  {code: 'PA', displayRegion: 'contiguous'},
  {code: 'RI', displayRegion: 'contiguous'},
  {code: 'SC', displayRegion: 'contiguous'},
  {code: 'SD', displayRegion: 'contiguous'},
  {code: 'TN', displayRegion: 'contiguous'},
  {code: 'TX', displayRegion: 'contiguous'},
  {code: 'UT', displayRegion: 'contiguous'},
  {code: 'VT', displayRegion: 'contiguous'},
  {code: 'VA', displayRegion: 'contiguous'},
  {code: 'WA', displayRegion: 'contiguous'},
  {code: 'WV', displayRegion: 'contiguous'},
  {code: 'WI', displayRegion: 'contiguous'},
  {code: 'WY', displayRegion: 'contiguous'},
  {code: 'DC', displayRegion: 'contiguous'},
];

export const STATE_GAP_MAP_GEOMETRY_BY_CODE = new Map(
  STATE_GAP_MAP_GEOMETRIES.map(geometry => [geometry.code, geometry]),
);
