import {eTag} from '@tinyhttp/etag';

import {STALE_WHILE_REVALIDATE_ONE_DAY} from '@/cache/constants';
import {isIndexableHost} from '@/config/indexing';

// Ensure robots.txt is not static generated by the Next.js build
export const dynamic = 'force-dynamic';

const DISALLOW_ALL_RULE = `User-Agent: *
Disallow: /`;

/**
 * `isIndexableHost` has already checked the host against the production
 * canonical allowlist, so the request host is the right sitemap origin.
 */
function getSitemapDirective(host: string | null) {
  return `Sitemap: https://${host}/sitemap.xml`;
}

/**
 * GET /robots.txt
 * Returns a robots.txt file that disallows all crawling in non-production
 * environments, and advertises the sitemap everywhere else.
 */
export async function GET(request: Request) {
  if (!isIndexableHost(request.headers.get('host'))) {
    return new Response(DISALLOW_ALL_RULE, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Cache-Control': STALE_WHILE_REVALIDATE_ONE_DAY,
        ETag: eTag(DISALLOW_ALL_RULE),
      },
    });
  }

  const sitemapDirective = getSitemapDirective(request.headers.get('host'));

  return new Response(sitemapDirective, {
    status: 200,
    headers: {
      'Content-Type': 'text/plain',
      'Cache-Control': STALE_WHILE_REVALIDATE_ONE_DAY,
      ETag: eTag(sitemapDirective),
    },
  });
}
